/* tslint:disable */
/* eslint-disable */
/**
 * PUT REST API
 * モバイルアプリハンズオンで作成するPUTアプリのREST API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ゴミ拾い
 * @export
 * @interface Trash
 */
export interface Trash {
    /**
     * ゴミ拾いのID
     * @type {number}
     * @memberof Trash
     */
    id: number;
    /**
     * ゴミ拾いイメージのURL
     * @type {string}
     * @memberof Trash
     */
    imageUrl: string;
    /**
     * ゴミ拾いの登録日
     * @type {string}
     * @memberof Trash
     */
    date: string;
    /**
     * ゴミ拾いのポイント
     * @type {number}
     * @memberof Trash
     */
    point: number;
}

export function TrashFromJSON(json: any): Trash {
    return TrashFromJSONTyped(json, false);
}

export function TrashFromJSONTyped(json: any, ignoreDiscriminator: boolean): Trash {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'imageUrl': json['imageUrl'],
        'date': json['date'],
        'point': json['point'],
    };
}

export function TrashToJSON(value?: Trash | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'imageUrl': value.imageUrl,
        'date': value.date,
        'point': value.point,
    };
}


