version: '3.7'

services:
  prism:
    image: stoplight/prism:3
    restart: always
    ports:
      - 9080:9080
    volumes:
      - ..:/app
    command: mock -p 9080 -h 0.0.0.0 /app/openapi/openapi.yaml